### ISSUE TITLE
Make player stranded

### ISSUE THREAD

**Issue by GlitchRemo** [step-9/cluedo-bloodhounds#19]
As a player
I want to get informed if I made wrong accusation
So that I can know the correct killer combination and remain in the game for invalidation

Acceptance Criteria:

- [x] Criteria 1:

Given it's my turn
When I accuse wrong
Then I should get stranded and I should get to know the murder combination

- [x] Criteria 2:

Given the game is going on
When I am stranded
Then I shouldn't get any turn

- [x] Criteria 3:

Given it's not my turn
When other player have accused
And the player's accusation is wrong
Then I should get a pop up that who is stranded
And the game should go on

- [x] Criteria 4:

Given it's not my turn
When all players are stranded
Then the game should end

**Comment by SaumaSaha** [comment]
Enhancement:
