### ISSUE TITLE
Change position of the suspected pawn

### ISSUE THREAD

**Issue by GlitchRemo** [step-9/cluedo-bloodhounds#31]
As a player
I want to see the character pawn that I suspect in the suspected room
So that I know whom I am suspecting

Acceptance Criteria:

- [x] Criteria 1:

Given it's my turn
When I suspect a character
Then the character pawn should be moved to the suspected room

- [x] Criteria 2:

Given it's not my turn
When someone suspect's my character
Then my character pawn should be moved to the suspected room

**Comment by SaumaSaha** [comment]
Player with the moved character should be able to suspect on their turn
